dist: xenial
sudo: false

language: generic

env:
  matrix:
    - KONG_TEST_DATABASE=postgres
    - KONG_TEST_DATABASE=cassandra

install:
  - make setup_tests
  - ./kong-build-tools/.ci/setup_ci.sh
script:
  - make test