apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.kongAppName }}
spec:
  replicas: {{ .Values.kongInstanceCount }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-{{ .Values.kongAppName }}
        app:  {{ .Release.Name }}-{{ .Values.kongAppName }}
    spec:
      containers:
      - name: kong
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: "off"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_LOG_LEVEL
            value: {{ .Values.kong.database.KONG_LOG_LEVEL }}
        {{ if .Values.kong.database.useCassandra }}
          - name: KONG_DATABASE
            value: "cassandra"
          {{ if .Values.provisionDB }}
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: {{ .Release.Name }}-{{ .Values.kong.database.name }}.{{ .Release.Namespace }}.svc.cluster.local
          {{ else }}
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: {{ .Values.kong.database.cassandra.contactPoints }}
          {{end}}
          - name: KONG_CASSANDRA_PORT
            value: {{ .Values.kong.database.cassandra.port }}
          - name: KONG_CASSANDRA_KEYSPACE
            value: {{ .Values.kong.database.cassandra.keyspace}}
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: {{ .Values.kong.database.cassandra.replcation | quote }}
        {{ else }}
          - name: KONG_PG_DATABASE
            value: {{ .Values.kong.database.postgres.database }}
          - name: KONG_PG_USER
            value: {{ .Values.kong.database.postgres.user }}
          - name: KONG_PG_PASSWORD
            value: {{ .Values.kong.database.postgres.password }}
          {{ if .Values.provisionDB }}
          - name: KONG_PG_HOST
            value: {{ .Release.Name }}-{{ .Values.kong.database.name }}.{{ .Release.Namespace }}.svc.cluster.local
          {{ else }}
          - name: KONG_PG_HOST
            value: {{ .Values.kong.database.postgres.host }}
          {{ end }}
          - name: KONG_PG_PORT
            value: {{ .Values.kong.database.postgres.port }}
        {{ end }}
        command: [ "/bin/sh", "-c", "kong start --run-migrations --vv" ]
        ports:
        - name: admin
          containerPort: {{ .Values.kong.admin.containerPort }}
          protocol: TCP
        - name: admin-ssl
          containerPort: {{ .Values.kong.admin.containerSSLPort }}
          protocol: TCP
        - name: proxy
          containerPort: {{ .Values.kong.proxy.containerPort }}
          protocol: TCP
        - name: proxy-ssl
          containerPort: {{ .Values.kong.proxy.containerSSLPort }}
          protocol: TCP
