apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-admin
spec:
  type: {{ .Values.kong.admin.type }}
  {{- if and (eq .Values.kong.admin.type "LoadBalancer") .Values.kong.admin.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kong.admin.loadBalancerIP }}
  {{- end }}
  ports:
  {{- if .Values.kong.admin.useTLS }}
  - name: kong-admin-ssl
    port: {{ default 8444 .Values.kong.admin.serviceSSLPort }}
    targetPort: {{ default 8444 .Values.kong.admin.containerSSLPort }}
    protocol: TCP
  {{- else }}
  - name: kong-admin
    port: {{ default 8001 .Values.kong.admin.servicePort }}
    targetPort: {{ default 8001 .Values.kong.admin.containerPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.kong.enterprise }}
  - name: kong-admin-gui
    port: {{ .Values.kong.admin.serviceGUIPort }}
    targetPort: {{ .Values.kong.admin.containerGUIPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ template "kong.fullname" . }}
