apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kongproxy
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy
    port: {{ .Values.services.proxyService.servicePort }}
    targetPort: {{ .Values.services.proxyService.containerPort }}
    protocol: TCP
  - name: kong-proxy-ssl
    port: {{ .Values.services.proxyService.serviceSslPort }}
    targetPort: {{ .Values.services.proxyService.containerSslPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.kongName }}


