apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kongadmin
spec:
  type: ClusterIP
  ports:
  - name: kong-admin
    port: {{ .Values.services.adminService.servicePort }}
    targetPort: {{ .Values.services.adminService.containerPort }}
    protocol: TCP
  - name: kong-admin-ssl
    port: {{ .Values.services.adminService.serviceSslPort }}
    targetPort: {{ .Values.services.adminService.containerSslPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.kongName }}