apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-proxy
spec:
  type: {{ .Values.kong.proxy.type }}
  {{- if and (eq .Values.kong.proxy.type "LoadBalancer") .Values.kong.proxy.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kong.proxy.loadBalancerIP }}
  {{- end }}
  ports:
  {{- if .Values.kong.proxy.useTLS }}
  - name: kong-proxy-ssl
    port: {{ default 8443 .Values.kong.proxy.serviceSSLPort }}
    targetPort: {{ default 8443 .Values.kong.proxy.containerSSLPort }}
    protocol: TCP
  {{ else }}
  - name: kong-proxy
    port: {{ default 8000 .Values.kong.proxy.servicePort }}
    targetPort: {{ default 8000 .Values.kong.proxy.containerPort }}
    protocol: TCP
  {{ end }}
  selector:
    app: {{ template "kong.fullname" . }}
